### ISSUE TITLE
No music. v.10-alpha

### ISSUE THREAD

**Issue by DexterLIM** [ronanhall/Mobility_Game#18]
Tested on v.10-alpha

Bug description

On v.10-alpha, there is no music or sound effects at all.
 

Steps to reproduce the behaviour:
1. Open game
2. Found the issue.

Expected behaviour:
I expected the music to work fine, as well as the sound effects.

Ran on OS win10

**Comment by ronanhall** [comment]
It was just a setting that was selected, I have unselected it and the music works now
