### ISSUE TITLE
Endpoint may need to be more obviosu

### ISSUE THREAD

**Issue by DexterLIM** [ronanhall/Mobility_Game#24]
Tested on Molibity v.0.13-alpha

  Endpoint may need to be more obvious
-Make the endpoint more clearly visible on the level.
-Add text or an icon to the level indicating the endpoint.
-Add a guide to the game that points to the endpoint.
 (This issue mostly happen to the Toy Room level)
-Adding lights or making it bright. This would allow players to see where the endpoint is.

**Comment by ronanhall** [comment]
finished
