### ISSUE TITLE
Tutorial level issues/improvement

### ISSUE THREAD

**Issue by DexterLIM** [ronanhall/Mobility_Game#29]
Tested on Molibity v.0.13-alpha

![tut 1](https://user-images.githubusercontent.com/101613042/195447727-c4d25635-5efc-4d3f-827a-82cb14f91eba.jpeg)
Make this place a bit longer.

![tut 2](https://user-images.githubusercontent.com/101613042/195447733-0a9c6dee-9cb9-4036-b294-24e2add4f968.jpeg)
This place has a bug where you need to be crouched but can stand.

Exoected behaviour
Expected to be crouched only.

To reproduce:
1. Start tutorial
2. Arriving at the place to learn crouch
3. Crouch and go
4. Issue found

**Comment by ronanhall** [comment]
fixed by adding a sphere collider of sorts to the players head that checks if there is a ceiling above them. If there is, they cant stand up
